name: Lint-GS

on:
  workflow_dispatch:

  schedule:
    - cron: '5 0/6 * * *'
    # - cron: '0/10 * * * *'
    # 表达式生成  https://crontab.guru/
    # - cron: "0 0,12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a pr-lint
        run: |
            export PGS=${{ secrets.PGS }}
            bash ./pubspec
